name = "backend"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[vars]
JWT_SECRET = "super-secret-key-change-in-production"
IMGBB_API_KEY = "VUI_LONG_NHAP_API_KEY_CUA_BAN_VAO_DAY"

[[d1_databases]]
binding = "DB"
database_name = "callteam_db"
database_id = "60261bfe-c8f1-4d2d-8e55-1d78c1036440"

[[durable_objects.bindings]]
name = "ROOM_SESSION"
class_name = "RoomSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomSession"]
